### PR TITLE
chore: bump up react-native dependencies

### PR DESCRIPTION
**Pull request by abdelhamid-f-nasser**
- Upgrade RN and Jest and all dependencies for the example app 
- Migrate android to RN 0.72.3 following the steps mentioned in [upgrade helper](https://react-native-community.github.io/upgrade-helper/)
- Bump Up all dependencies for the SDK (all except for TS)
- Migrate and adjust imports of the new jest `mocked` which moved got moved `jest-mock`

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

[MOB-12699](https://instabug.atlassian.net/browse/MOB-12699)

### Development

- [x] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [x] E2E Succeeds for iOS
- [x] E2E succeeds for Android
- [x] unit tests succeeds

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] Issue from task tracker has a link to this pull request

[MOB-12699]: https://instabug.atlassian.net/browse/MOB-12699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by abdelhamid-f-nasser** [comment]
@a7medev  Here's the test results for the upgraded SDK against the  following versions

| Version | build-sdk | SDK testing | onInvokeHandler | onSDKDismissedHandler | onReportSubmitHandler |
| ------- |:---------:|:-----------:|:---------------:|:---------------------:|:---------------------:|
| 0.60.X  |    ❌     |     ❌      |       ❌        |          ❌           |          ❌           |
| 0.63.X  |    ❌     |     ❌      |       ❌        |          ❌           |          ❌           |
| 0.64.X  |    ✅     |     ✅      |       ❌        |          ❌           |          ❌           |
| 0.65.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| 0.66.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| 0.67.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| 0.68.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| 0.70.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| 0.72.X  |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           |
| default |    ✅     |     ✅      |       ✅        |          ✅           |          ✅           | 

Please check these results and let me know how we would proceed

**Comment by a7medev** [comment]
Very great effort testing this @abdelhamid-f-nasser! 👏🏼
Can you please confirm if our callbacks (e.g. `onInvokeHandler`, `onSDKDismissedHandler`, and `onReportSubmitHandler`) work fine on React Native 0.64 and our **production** version of the SDK (`yarn add instabug-reactnative@latest`) or if they are broken in the production SDK as well?

**Comment by abdelhamid-f-nasser** [comment]
Thank you @a7medev. 🙏 

I've checked React Native 0.64 against the latest production version of the SDK, and none of the `event handlers` are being triggered as well. Let's check maybe there is a slight mis-configuration.

**Comment by abdelhamid-f-nasser** [comment]
We need to squash the following commits:
	chore(Dependencies): Upgrade RN and jest
	chore(Android): Migrate to RN 0.72.3
	chore(Deps): Upgrade root packages
	refactor(test): Migrate mocked imports
	style: Fix format issues
	build(ci): upgrade Node.js to v18.17.0 
	chore(Git): Un-track main.jsbundle.map


as this contains a different merged PR: chore: add auto device selection detection #1009 

Lastly we need to Rebase and merge so the two commits (PR ones) are shown in the dev branch tree

**Review by a7medev — APPROVED** [review]

**Review by asamiz — APPROVED** [review]
Good job @abdelhamid-f-nasser, this is an approval from my side, but I think you need to add the changes especially the Android migration part on the CHNGSLOG file.

**Comment by abdelhamid-f-nasser** [comment]
@asamiz @a7medev  Could you please review and provide feedback on the two entries in the  `CHANGELOG.md` ***"Changed"*** section.

```md
### Changed

- Bump react-native SDK dependencies (except for TS) ([#1007](https://github.com/Instabug/Instabug-React-Native/pull/1007))
- Migrate Android following the migration guide for react-native 0.72.3 ([#1007](https://github.com/Instabug/Instabug-React-Native/pull/1007))
```
Thank you guys for the encouragement and for the thorough review.

**Pull request merged**
