### PR TITLE
[MOB-9969] Change Directory Structure

### PR DESCRIPTION
**Pull request by TheBuggedYRN**
## Description of the change

Introduce a new directory structure that's less polluted, and groups related files together:

```bash
.
├── example/ # Previously InstabugSample
├── src/
│   ├── models/
│   ├── modules/
│   ├── utils/
│   ├── index.d.ts
│   └── index.js
├── tests/
│   ├── jest/
│   └── *.spec.js
└── ...
```

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by a7med-mahmoud** [comment]
Renaming `InstabugSample` to `example` will affect #779, should we move that change there maybe?

**Comment by TheBuggedYRN** [comment]
> Renaming `InstabugSample` to `example` will affect #779, should we move that change there maybe?

@a7med-mahmoud I think we will just stick with rebase after one gets merged, it should be straight forward.

**Comment by a7med-mahmoud** [comment]
> > Renaming `InstabugSample` to `example` will affect #779, should we move that change there maybe?
> 
> @a7med-mahmoud I think we will just stick with rebase after one gets merged, it should be straight forward.

@TheBuggedYRN Are you sure that rebasing will resolve file structure changes?

**Comment by TheBuggedYRN** [comment]
> > > Renaming `InstabugSample` to `example` will affect #779, should we move that change there maybe?
> > 
> > 
> > @a7med-mahmoud I think we will just stick with rebase after one gets merged, it should be straight forward.
> 
> @TheBuggedYRN Are you sure that rebasing will resolve file structure changes?

@a7med-mahmoud It will, with some manual effort.

**Review by a7med-mahmoud — APPROVED** [review]

**Review by DavidMina96 — APPROVED** [review]

**Review by AliAbdelfattah — APPROVED** [review]

**Pull request merged**
